### PR TITLE
fix: use `rspack.DefinePlugin`

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes https://github.com/rspack-contrib/rspack-plugins/issues/8

### CODE REVIEW

**Review by hardfist — APPROVED** [review]

**Comment by hardfist** [comment]
waiting for the new release

**Comment by hardfist** [comment]
@dmathisen try 0.0.3

**Comment by hardfist** [comment]
> rspack-plugins docs

sorry we forget to update the repo link, the archived repo is moved to rspack-plugin monorepo for better maintenance.

**Comment by hardfist** [comment]
@dmathisen is 0.0.3 ok?

**Comment by dmathisen** [comment]
@hardfist Thanks for the followup! I'm sorry if I'm being dumb, but I'm still a bit lost. I only see 0.0.2 available (looking [here](https://www.npmjs.com/package/rspack-plugin-dotenv)). Maybe I'm just looking at the wrong thing.

**Comment by hardfist** [comment]
https://www.npmjs.com/package/rspack-plugin-dotenv/v/0.0.3 @dmathisen

**Comment by dmathisen** [comment]
@hardfist I'm getting an error

`const DotenvPlugin = require('rspack-plugin-dotenv');`
...
```js
[79] plugins: [
[80]   new DotenvPlugin({ path: `./.env.${envvar}` }),
[81] ]
```

image

**Comment by bvanjoi** [comment]
> I'm getting an error that DotenvPlugin is not a constructor

I am unable to reproduce this error locally. My local setup is as follows:

```
// package.json
{
  "depedencies": {
     "@rspack/cli": "0.3.10",
     "rspack-plugin-dotenv": "0.0.3"
  }
}

// rspack.config.js

const { DotenvPlugin } =require('rspack-plugin-dotenv');
const { defineConfig } = require('@rspack/cli');
const base = defineConfig({
	devtool: 'source-map',
  entry: path.resolve(__dirname, "./src/index.js"),
  mode: 'development',
	plugins: [
		new DotenvPlugin({ path: './.env'}),
	]
});

module.exports = base
```

run `npx rspack build`

**Comment by hardfist** [comment]
> @hardfist I'm getting an error that **DotenvPlugin is not a constructor**
> 
> `const DotenvPlugin = require('rspack-plugin-dotenv');` ...
> 
> ```js
> [79] plugins: [
> [80]   new DotenvPlugin({ path: `./.env.${envvar}` }),
> [81] ]
> ```
> 
> image
> 
> I've also tried `const { DotenvPlugin } = require('rspack-plugin-dotenv');`
> 
> Would you like me to create a separate issue for this?

can you help provide a repro

**Comment by dmathisen** [comment]
@bvanjoi @hardfist It's working as your setup shows! I apologize for wasting any time here.

This works
`const { DotenvPlugin } = require('rspack-plugin-dotenv');`

No other variations work
`const Dotenv = require('rspack-plugin-dotenv');`
`const DotenvPlugin = require('rspack-plugin-dotenv');`
`const { Dotenv } = require('rspack-plugin-dotenv');`

I just didn't try the correct import, I guess. Maybe if I convert to `.ts` it would've shown that my import was incorrect. But I'm all set now, everything is working well!

In any case, I guess the doc [here](https://github.com/rspack-contrib/rspack-plugins/tree/main/packages/plugin-dotenv) should be updated to show that the import needs to be `{ DotenvPlugin }`.

Thank you so much! I'll stick to using the alpha 0.0.3 release until the public release is available.

**Pull request merged**
